name: Python CI

on:
  push:
    branches:
      - master  # Déclencher sur les push vers la branche master
  pull_request:
    branches:
      - master  # Déclencher sur les pull requests vers la branche master

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser la dernière version de Ubuntu

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Spécifier la version de Python à utiliser

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install  # Installer les dépendances via Poetry

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          poetry run pytest  # Exécuter les tests avec pytest

      # Étape 5 : Nettoyage (optionnel)
      - name: Clean up
        run: |
          # Vous pouvez ajouter des étapes pour nettoyer ou archiver les résultats, si nécessaire
